### ISSUE TITLE
vs2015 Compile error

### ISSUE THREAD

**Issue by ZhaoxingNiu** [espdev/csaps-cpp#1]
The code runs successfully in Linux.
In visual studio 2015, there is a compile error.
I modify 
`const DoubleArray SolveLinearSystem(const DoubleSparseMatrix &A,const DoubleArray &b);` to 
`const DoubleArray SolveLinearSystem(const DoubleSparseMatrix &A, DoubleArray &b);`,
then  the error is solved.

**Comment by espdev** [comment]
@ZhaoxingNiu Hi,

I have tested the code in VS Community 2015 Update 3 and I did not got any compile errors.

The function signature in my case:
```cpp
DoubleArray SolveLinearSystem(const DoubleSparseMatrix &A, const DoubleArray &b);
```
See: https://github.com/espdev/csaps-cpp/blob/master/src/csaps.h#L38

Two questions:
* What version of Eigen do you use? 
* What compile error do you get?

**Comment by ZhaoxingNiu** [comment]
Sorry for getting back to you so late.

The answer:
 -  Eigen version is 3.3.3
 - The error is  as follows:
![image](https://user-images.githubusercontent.com/9906923/54196779-2d5d1380-44fd-11e9-89ff-b5d74013b647.png)

**Comment by espdev** [comment]
@ZhaoxingNiu Thanks! I will check it.

**Comment by espdev** [comment]
@ZhaoxingNiu I have checked and can confirm this error for Eigen 3.3.3. I think, you should use Eigen 3.3.4 or newer. It seems we encountered with this [bug](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1410) (`Bug 1410: lvalue propagation of Array/Matrix-Wrapper with a const nested expression.`) that was [fixed](http://eigen.tuxfamily.org/index.php?title=ChangeLog#Eigen_3.3.4) in 3.3.4 version. Also I have checked compilation with Eigen 3.3.4 and it was finished without any errors.
