### ISSUE TITLE
What's the equation of CubicSmoothingSpline?

### ISSUE THREAD

**Issue by jiayily** [espdev/csaps-cpp#2]
Hi, can you please show me the equation of CubicSmoothingSpline used in your code?

**Comment by espdev** [comment]
@Jiayi719 
You can refer to the documentation of Python module:
https://csaps.readthedocs.io/en/latest/formulation.html

Full mathematical description, equations and algorithm can be found in the book: C. de Boor, A Practical Guide to Splines
