### ISSUE TITLE
Issue with Eigen?

### ISSUE THREAD

**Issue by Amit-Nayak-2000** [espdev/csaps-cpp#3]
Im trying to create a smoothing spline with a dataset (it worked successfully in Matlab), but for some reason i keep getting this error when trying to create it:

Assertion failed: (m_factorizationIsOk && "The matrix should be factorized first"), function _solve_impl, file ./eigen-3.4.0/Eigen/src/SparseLU/SparseLU.h, line 317.

Do you know what could be causing a dataset to cause this error?

**Comment by espdev** [comment]
Hello @Amit-Nayak-2000,

I think in your case the factorization does not work for some reason.

https://github.com/espdev/csaps-cpp/blob/41a67952e7ea71c05f76b6cb1f178825c576a981/src/csaps.cpp#L107-L121

See also notes from the [documentation](https://eigen.tuxfamily.org/dox/classEigen_1_1SparseLU.html):

> Unlike the initial [SuperLU](https://eigen.tuxfamily.org/dox/classEigen_1_1SuperLU.html) implementation, there is no step to equilibrate the matrix. For badly scaled matrices, this step can be useful to reduce the pivoting during factorization. If this is the case for your matrices, you can try the basic scaling method at "unsupported/Eigen/src/IterativeSolvers/Scaling.h"

**Comment by kchenna-nimble** [comment]
I am running into the same issue when I use weights for smoothing. here is an example test case

```cpp
  SECTION("weighted smoothing") {
    const size_t pcount = 13;

    csaps::DoubleArray xdata(pcount);
    xdata << 0, 0.833333, 1.66667, 
            2.5, 3.33333, 4.16667, 
            5, 5.83333, 6.66667, 
            7.5, 8.33333, 9.16667, 10;

    csaps::DoubleArray ydata(pcount);
    ydata << 0.8718, 0.918648, 0.651237, 
             0.646737, 0.642237, 0.637737, 
             0.633237, 0.628737, 0.624237, 
             0.619737, 0.615237, 0.610737, 0.606237;

    csaps::DoubleArray weights(pcount);
    weights << -900, -733.333, -566.667, 
               -400, -233.333, -66.6667, 
               100, 266.667, 433.333, 
               600, 766.667, 933.333, 1100;

    const size_t xidata_size = 120;

    csaps::UnivariateCubicSmoothingSpline sp(xdata, ydata, weights, 0.8);

    csaps::DoubleArray xi = csaps::DoubleArray::LinSpaced(25, 0, 10);
    std::cout << sp(xi);
  }
```
