### ISSUE TITLE
Access Violation error upon Constructor call

### ISSUE THREAD

**Issue by jaredlawson** [espdev/csaps-cpp#4]
I am using Eigen 3.4.0 and the csaps functionality to fit a smoothing spline. I am able to compile successfully (Visual Studio 2015) yet when I run the constructor instantiating the UnivariateCubicSmoothingSpline, I get an Access Violation Error that crashes my program. My syntax follows identically to the examples in the tests folder provided. My relevant code is below (error caused by line 115). Please let me know if you have any recommendation!

![image](https://user-images.githubusercontent.com/69919616/177426566-2054ae2d-fb11-4f6b-be4a-1cd7693a0d8d.png)

**Comment by espdev** [comment]
Hello @jaredlawson,

I think you need to allocate `weights` array to your data size: `centerpixels.size()`
Also try to create spline without `weights` argument.

**Comment by jaredlawson** [comment]
Hello @espdev ,
I first attempted the constructor without `weights`, and had the same result. I've also commented the constructor with `weights` allocated as shown and it has not given a problem.

One thing that may be different than normal use case is that I am calling this within a Mex function. I'm linking everything necessary and am able to compile but maybe there is something specific to Mex that is giving me a problem.

**Comment by espdev** [comment]
A Mex function for MATLAB, is it?
Have you considered using [csaps](https://www.mathworks.com/help/curvefit/csaps.html) function from MATLAB?

**Comment by jaredlawson** [comment]
Yes! My current backup plan is to use the MATLAB csaps function but I was thinking I could get improved efficiency porting this into CPP.

**Comment by espdev** [comment]
Eigen based implementation is not so fast. Also, this implementation does not work with vectorization. So I can assume that csaps function from MATLAB will be even more effective. But you may have the overhead of copying data.

**Comment by jaredlawson** [comment]
Thanks for the advice. I think I will stick with MATLAB csaps. I'll close this issue.
