### ISSUE TITLE
smoothing parameter highly dependent on scale of x-axis

### ISSUE THREAD

**Issue by montanaviking** [espdev/csaps-cpp#7]
I am attempting to smooth RF circuit (S-parameters) data vs frequency. The real and imaginary parts are smoothed separately as DoubleArrays and the frequency is in Hz and ranges up to 25E9 Hz. These high values in the frequency (x-axis) result in no smoothing until the smoothing parameter is set to something like 1E-25. To work around, I scale the x-axis, apply smoothing with a reasonable smoothing parameter, on the order of 0.8 or so, and then unscale the x-axis (frequency) to get back the original frequency scale.
This works but requires one to derive a scaling factor from the x-axis values, perhaps by using an average of the x-axis values?
If you like, I can send up an example program to illustrate.
Then again, I haven't looked deeply into this and the problem could well be my misunderstanding of how to use the software?
Thanks and best, Phil

**Comment by montanaviking** [comment]
Hi, It appears that the dependence of the smoothing parameter on the x-range values is normal for other versions of this algorithm https://csaps.readthedocs.io/en/latest/tutorial.html
which talks about "Smooth normalization". I'm still new to this code as of yesterday and in all fairness, this probably isn't a "bug" but is normal for this algorithm. In the Python version (see link) the "Smooth normalization" is apparently a recent feature.
In any case, thanks again to the developers!

**Comment by espdev** [comment]
Yes, C++ package currently does not support [smooth normalization](https://csaps.readthedocs.io/en/latest/tutorial.html#smooth-normalization).
